AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    Architectures: [x86_64]
    Timeout: 15
    MemorySize: 256
    Environment:
      Variables:
        APP_ENV: dev
        DEMO_MODE: "true"
        FRONTEND_ORIGIN: "*"
        KEYCLOAK_SERVER_URL: "https://keycloak-3a73e53a-a0c9-4484-ba06-7bfbeca55673.moonshard-wow.com"
        KEYCLOAK_REALM: "academic-requests"
        KAFKA_BOOTSTRAP_SERVERS: "kafka-c820a368-3fd9-49da-9acc-0a8af269072a.moonshard-wow.com"
        KAFKA_TOPIC_REQUESTS: "academic-requests-topic"
        KAFKA_TOPIC_REVIEWS: "academic-reviews"
        KAFKA_TOPIC_NOTIFICATIONS: "academic-notifications"
        KAFKA_TOPIC_ANALYTICS: "academic-analytics"

Resources:
  AcademicRequestsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: [GET, POST, OPTIONS]
        AllowHeaders: [Content-Type, X-Request-Id, Authorization]

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref AcademicRequestsApi
            Path: /
            Method: ANY
            PayloadFormatVersion: "2.0"
        Proxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref AcademicRequestsApi
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

Outputs:
  ApiUrl:
    Value: !Sub "https://${AcademicRequestsApi}.execute-api.${AWS::Region}.amazonaws.com"
